name: 'Check if affected 👁️'
description: 'Check if paths are affected by changes'
inputs:
  path_filters:
    description: 'Path filters to use'
    required: true

outputs:
  is_affected:
    description: 'Whether the nx cache was hit or not'
    value: ${{ steps.check_filters.outputs.is_affected }}

runs:
  using: 'composite'
  steps:
    - name: 'Get base 📦'
      id: get_base
      uses: nrwl/nx-set-shas@v4

    - name: 'Check diff for file paths'
      id: check_filters
      shell: bash
      run: |
        echo "Checking if '${{ inputs.path_filters }}' has been affected in git since ${{ steps.get_base.outputs.base }}"
        files_changed=$(git diff --name-only ${{ steps.get_base.outputs.base }})
        echo "is_affected=$(echo $files_changed | grep -E '${{ inputs.path_filters }}' | wc -l)" >> $GITHUB_OUTPUT
