name: 'Install Dependencies 🪇'
description: 'Install dependencies and set NX cache'

runs:
  using: 'composite'
  steps:
    - uses: volta-cli/action@v4
      with:
        package-json-path: '${{ github.workspace }}/package.json'

    - uses: chill-viking/npm-ci@v1
      name: 'npm CI'
