name: 'Install Dependencies 🪇'
description: 'Install dependencies and set NX cache'

runs:
  using: 'composite'
  steps:
    - uses: volta-cli/action@v4
      with:
        package-json-path: '${{ github.workspace }}/package.json'

    - name: Use the package manager cache if available
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: "npm-packages-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}"
        restore-keys: |
          npm-packages-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: npm ci
