name: 'Requires enlightenment 🕯️'
description: 'Request improvement to documentation or highlight missing or misaligned documentation'
title: '[🕯️]: '
labels: ['📝 documentation', '🚨 urgent', '🙋‍♂️ question']
assignees:
  - peterjokumsen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!
  - type: textarea
    attributes:
      label: Documentation request
      description: Please describe what area needs improved documentation
      placeholder: |
        The documentation for `PjLogger` does not describe how to use the service.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested points to cover
      description: How can the documentation be improved?
      placeholder: |
        - Describe the property `to`
        - Include why the service was created
        - How can it be extended for other uses?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional details
      description: |
        Links? References? Anything that will give me more context about the missing information!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
